envGroups:
  - name: backend-secrets
  - name: frontend-secrets
services:
  - type: pserv
    name: backend
    runtime: docker
    dockerContext: ./server
    dockerfilePath: ./server/Dockerfile
   
    envGroup: backend-secrets

  - type: web
    name: seo-frontend
    runtime: docker
    dockerContext: ./client
    dockerfilePath: ./client/Dockerfile
    envGroup: frontend-secrets
