# render.yaml
# A simplified and direct version to satisfy the Render parser.
# We will link to secrets in the Render Dashboard UI after this is accepted.

services:
  # 1. The Backend Service (Private)
  - type: pserv
    name: backend # This name MUST match the 'proxy_pass' in your default.conf
    runtime: docker
    dockerContext: ./server
    dockerfilePath: ./server/Dockerfile
    envVars:
      # Using a placeholder value to pass validation.
      - key: GEMINI_API_KEY
        value: "placeholder_gemini_key"

  # 2. The Frontend Service (Public)
  - type: web
    name: seo-frontend
    runtime: docker
    dockerContext: ./client
    dockerfilePath: ./client/Dockerfile
    envVars:
      # Using placeholder values to pass validation.
      - key: VITE_FIREBASE_API_KEY
        value: "placeholder_firebase_key"
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: "placeholder_auth_domain"
      - key: VITE_FIREBASE_PROJECT_ID
        value: "placeholder_project_id"
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: "placeholder_storage_bucket"
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: "placeholder_messaging_id"
      - key: VITE_FIREBASE_APP_ID
        value: "placeholder_app_id"
      - key: VITE_FIREBASE_MEASUREMENT_ID
        value: "placeholder_measurement_id"
